# TokyoNight Alacritty Theme (TOML)

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 6
y = 6

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[colors.normal]
black   = "0x15161e"
red     = "0xf7768e"
green   = "0x9ece6a"
yellow  = "0xe0af68"
blue    = "0x7aa2f7"
magenta = "0xbb9af7"
cyan    = "0x7dcfff"
white   = "0xa9b1d6"

[colors.bright]
black   = "0x414868"
red     = "0xf7768e"
green   = "0x9ece6a"
yellow  = "0xe0af68"
blue    = "0x7aa2f7"
magenta = "0xbb9af7"
cyan    = "0x7dcfff"
white   = "0xc0caf5"

[colors.cursor]
text   = "0x1a1b26"
cursor = "0xc0caf5"

[colors.selection]
text       = "0xc0caf5"
background = "0x283457"

[cursor]
style = "Beam"
unfocused_hollow = true

